import { NgModule } from '@angular/core';
import {
  // MatAutocompleteModule,
  MatButtonModule,
  MatButtonToggleModule,
  // MatCardModule,
  // MatCheckboxModule,
  MatChipsModule,
  // MatDatepickerModule,
  MatDialogModule,
  MatDividerModule,
  MatExpansionModule,
  // MatGridListModule,
  MatIconModule,
  // MatInputModule,
  // MatListModule,
  MatMenuModule,
  // MatNativeDateModule,
  // MatPaginatorModule,
  // MatProgressBarModule,
  // MatProgressSpinnerModule,
  // MatRadioModule,
  MatRippleModule,
  MatSelectModule,
  // MatSidenavModule,
  // MatSliderModule,
  // MatSlideToggleModule,
  // MatSnackBarModule,
  // MatSortModule,
  // MatStepperModule,
  // MatTableModule,
  // MatTabsModule,
  MatToolbarModule,
  MatTooltipModule
} from '@angular/material';

const materialImports = [
  // MatAutocompleteModule,
  MatButtonModule,
  MatButtonToggleModule,
  // MatCardModule,
  // MatCheckboxModule,
  MatChipsModule,
  // MatDatepickerModule,
  MatDialogModule,
  MatDividerModule,
  MatExpansionModule,
  // MatGridListModule,
  MatIconModule,
  // MatInputModule,
  // MatListModule,
  MatMenuModule,
  // MatNativeDateModule,
  // MatPaginatorModule,
  // MatProgressBarModule,
  // MatProgressSpinnerModule,
  // MatRadioModule,
  MatRippleModule,
  MatSelectModule,
  // MatSidenavModule,
  // MatSliderModule,
  // MatSlideToggleModule,
  // MatSnackBarModule,
  // MatSortModule,
  // MatStepperModule,
  // MatTableModule,
  // MatTabsModule,
  MatToolbarModule,
  MatTooltipModule
];

@NgModule({
  imports: [...materialImports],
  exports: [...materialImports]
})
export class CustomMaterialModule { }
